version: '3.8'

services:
  backend_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge