name: Automated unit and load test

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: MOTOR_INSURANCE_WEBSITE
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'v18.19.0'

      - name: Install and build
        run: |
          cd server
          npm i
          npm run build

      - name: Run unit test
        run: |
          cd server

          TOKEN_SECRET=$(openssl rand -base64 32 | tr -d '\n')
          echo "NESTAUTH_SECRET=$TOKEN_SECRET" >> $GITHUB_ENV

          npm run test:cov
        env:
          DB_HOSTNAME: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_NAME: MOTOR_INSURANCE_WEBSITE

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Start backend
        run: |
          cd server

          TOKEN_SECRET=$(openssl rand -base64 32 | tr -d '\n')
          echo "NESTAUTH_SECRET=$TOKEN_SECRET" >> $GITHUB_ENV

          npm run start &
        env:
          DB_HOSTNAME: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_NAME: MOTOR_INSURANCE_WEBSITE

      - name: Run load test
        run: |
          cd server
          npm run load-test

      - name: Stop backend
        run: kill $(jobs -p)

